#!/usr/bin/env python3
"""
Volatility Surface 3D Visualization
Reads CSV files generated by vol_surface_analysis.rs and creates interactive 3D plots
"""

import pandas as pd
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import sys

SYMBOLS = ["TSLA", "AAPL", "NVDA", "MSFT"]

def plot_vol_surface_3d(symbol):
    """Create 3D volatility surface plot for a symbol"""
    filename = f"{symbol.lower()}_vol_surface.csv"
    
    try:
        df = pd.read_csv(filename)
    except FileNotFoundError:
        print(f"❌ {filename} not found. Run vol_surface_analysis first.")
        return None
    
    if df.empty:
        print(f"⚠️  {symbol}: No data in CSV")
        return None
    
    # Separate calls and puts
    calls = df[df['OptionType'] == 'Call']
    puts = df[df['OptionType'] == 'Put']
    
    # Create 3D surface plot
    fig = go.Figure()
    
    if not calls.empty:
        fig.add_trace(go.Scatter3d(
            x=calls['Strike'],
            y=calls['TimeToExpiry'],
            z=calls['ImpliedVol'] * 100,
            mode='markers',
            marker=dict(size=5, color='green', opacity=0.8),
            name='Calls',
            text=calls.apply(lambda row: f"Strike: ${row['Strike']:.2f}<br>IV: {row['ImpliedVol']*100:.1f}%<br>Vol: {row['Volume']}", axis=1),
            hovertemplate='%{text}<extra></extra>'
        ))
    
    if not puts.empty:
        fig.add_trace(go.Scatter3d(
            x=puts['Strike'],
            y=puts['TimeToExpiry'],
            z=puts['ImpliedVol'] * 100,
            mode='markers',
            marker=dict(size=5, color='red', opacity=0.8),
            name='Puts',
            text=puts.apply(lambda row: f"Strike: ${row['Strike']:.2f}<br>IV: {row['ImpliedVol']*100:.1f}%<br>Vol: {row['Volume']}", axis=1),
            hovertemplate='%{text}<extra></extra>'
        ))
    
    fig.update_layout(
        title=f'{symbol} Volatility Surface',
        scene=dict(
            xaxis_title='Strike Price ($)',
            yaxis_title='Time to Expiry (years)',
            zaxis_title='Implied Volatility (%)',
            camera=dict(eye=dict(x=1.5, y=1.5, z=1.3))
        ),
        width=1000,
        height=700
    )
    
    return fig

def plot_vol_smile(symbol):
    """Create 2D volatility smile (IV vs Strike at fixed expiry)"""
    filename = f"{symbol.lower()}_vol_surface.csv"
    
    try:
        df = pd.read_csv(filename)
    except FileNotFoundError:
        return None
    
    if df.empty:
        return None
    
    # Group by expiry and plot each
    fig = go.Figure()
    
    for option_type in ['Call', 'Put']:
        data = df[df['OptionType'] == option_type].sort_values('Strike')
        
        if not data.empty:
            fig.add_trace(go.Scatter(
                x=data['Moneyness'],
                y=data['ImpliedVol'] * 100,
                mode='markers+lines',
                name=f'{option_type}s',
                marker=dict(size=8),
                line=dict(width=2),
                hovertemplate='Moneyness: %{x:.3f}<br>IV: %{y:.1f}%<extra></extra>'
            ))
    
    # Add vertical line at ATM (moneyness = 1.0)
    fig.add_vline(x=1.0, line_dash="dash", line_color="gray", 
                  annotation_text="ATM", annotation_position="top")
    
    fig.update_layout(
        title=f'{symbol} Volatility Smile',
        xaxis_title='Moneyness (Strike / Spot)',
        yaxis_title='Implied Volatility (%)',
        hovermode='closest',
        width=900,
        height=500
    )
    
    return fig

def plot_term_structure(symbol):
    """Plot volatility term structure (IV vs Time to Expiry)"""
    filename = f"{symbol.lower()}_vol_surface.csv"
    
    try:
        df = pd.read_csv(filename)
    except FileNotFoundError:
        return None
    
    if df.empty:
        return None
    
    # Filter ATM options (moneyness close to 1.0)
    atm_data = df[(df['Moneyness'] >= 0.95) & (df['Moneyness'] <= 1.05)]
    
    if atm_data.empty:
        print(f"⚠️  {symbol}: No ATM options found")
        return None
    
    fig = go.Figure()
    
    for option_type in ['Call', 'Put']:
        data = atm_data[atm_data['OptionType'] == option_type].sort_values('TimeToExpiry')
        
        if not data.empty:
            fig.add_trace(go.Scatter(
                x=data['TimeToExpiry'] * 365,  # Convert to days
                y=data['ImpliedVol'] * 100,
                mode='markers+lines',
                name=f'{option_type}s',
                marker=dict(size=10),
                line=dict(width=2),
                hovertemplate='Days: %{x:.0f}<br>IV: %{y:.1f}%<extra></extra>'
            ))
    
    fig.update_layout(
        title=f'{symbol} Volatility Term Structure (ATM Options)',
        xaxis_title='Days to Expiry',
        yaxis_title='Implied Volatility (%)',
        hovermode='closest',
        width=900,
        height=500
    )
    
    return fig

def create_multi_symbol_dashboard():
    """Create dashboard with all symbols"""
    print("=" * 70)
    print("VOLATILITY SURFACE VISUALIZATION")
    print("=" * 70)
    
    for symbol in SYMBOLS:
        print(f"\n📊 Processing {symbol}...")
        
        # 3D Surface
        fig_3d = plot_vol_surface_3d(symbol)
        if fig_3d:
            html_file = f"{symbol.lower()}_vol_surface_3d.html"
            fig_3d.write_html(html_file)
            print(f"  ✓ 3D surface → {html_file}")
        
        # 2D Smile
        fig_smile = plot_vol_smile(symbol)
        if fig_smile:
            html_file = f"{symbol.lower()}_vol_smile.html"
            fig_smile.write_html(html_file)
            print(f"  ✓ Vol smile → {html_file}")
        
        # Term Structure
        fig_term = plot_term_structure(symbol)
        if fig_term:
            html_file = f"{symbol.lower()}_term_structure.html"
            fig_term.write_html(html_file)
            print(f"  ✓ Term structure → {html_file}")
    
    print("\n" + "=" * 70)
    print("Done! Open HTML files in browser to view interactive plots.")
    print("=" * 70)

if __name__ == "__main__":
    try:
        create_multi_symbol_dashboard()
    except ImportError as e:
        print("❌ Missing required libraries. Install with:")
        print("   pip install pandas plotly")
        sys.exit(1)
